import Link from "next/link";

export default function HomePage() {
  return (
    <>
      <div className="min-h-screen w-full h-full flex flex-col gap-5 items-center justify-center">
        <h1 className="xl:text-5xl lg:text-5xl md:text-4xl text-3xl font-bold text-center">Private Swap Dex</h1>
        <div className="grid xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-2 grid-cols-1 gap-5 xl:w-1/3 lg:w-1/2 md:w-1/2 w-[95vw]">
          <Card href="/swap" title="SWAP" info="Swap 1000's of tokens across 300 different chains"/>
          <Card href="/revshare/mint" title="REV SHARE" info="Mint NFT's and collect a share of revenue generated by the swap"/>
        </div>
      </div>
    </>
  );
}

const Card = ({ title, href, info }: { title: string, href: string, info: string }) => {
  return (
    <Link href={href} className="primary-button shadow-sm shadow-shadow dark:shadow-dark-shadow grid-item rounded-lg p-5">
      <h2 className="font-bold">{title}</h2>
      <p className="text-sm opacity-80">{info}</p>
    </Link>
  )
}