import { type RequestError } from "./request";

export interface GetCurrencyResponse {
    name: string,
    symbol: string,
    network: Networks,
    contract_address: string | null,
    has_extra_id: boolean,
    extra_id: string,
    image: string,
    warnings_from: string[],
    warnings_to: string[],
    validation_address: string,
    validation_extra: string | null,
    address_explorer: string,
    tx_explorer: string,
    confirmations_from: string,
    isFiat: boolean
}

export interface OutputCurrency extends GetCurrencyResponse {
    placeholder: string
}

export interface Currency extends GetCurrencyResponse {
    isPair: boolean
}

export interface UseRangeState {
    loading: boolean,
    error: RequestError | undefined,
    response: GetRangeResponse | undefined
}

export interface GetRangeResponse {
    min: number | null,
    max: number | null
}

export interface UseCurrencyState {
    loading: boolean,
    error: RequestError | undefined,
    response: GetCurrencyResponse | undefined
}

export enum Currencies {
    BTC = "btc",
    ETH = "eth",
    USDC_ETH = "usdc"
}

export enum Networks {
    ETH = "eth",
    BSC = "bsc",
    AKT = "akt",
    BCH = "bch",
    ALGO = "algo",
    AMB = "amb",
    BAND = "band",
    ATOM = "atom",
    AVAX_X = "AVAX-X",
    AVAX_C = "avax-c",
    MATIC = "matic",
    SOLANA = "solana",
    KSM = "ksm",
    BASE = "base",
    BSV = "bsv",
    CELO = "celo",
    MODE = "mode",
    LUNA = "luna",
    RVN = "rvn",
    RUNE = "rune",
    ADA = "ada",
    OPTIMISM = "optimism",
    SYSNEVM = "sysnevm",
    CFG = "cfg",
    CKB = "ckb",
    KAS = "kas",
    SYS = "sys",
    TRX = "trx",
    LUNC = "lunc",
    DCR = "dcr",
    ARBITRUM = "arbitrum",
    KLAYTN = "klaytn",
    DOGE = "doge",
    CTXC = "ctxc",
    MOB = "mob",
    EGLD = "egld",
    EOS = "eos",
    CMT = "cmt",
    ZKSYNC = "zksync",
    ZKSYNC_OTHER = "zkSync",
    BRC = "brc",
    FLOW = "flow",
    SUI = "sui",
    KCC = "kcc",
    HBAR = "hbar",
    CROEVM = "croevm",
    METIS = "metis",
    ICP = "icp",
    IOST = "iost",
    IOTA = "iota",
    TON = "ton",
    KAVA = "kava",
    KLV = "klv",
    SDN = "sdn",
    NEAR = "near",
    LTC = "ltc",
    GATECHAIN = "gatechain",
    NULS = "nuls",
    OAS = "oas",
    ACTEVM = "actevm",
    QTUM = "qtum",
    RBTC = "rbtc",
    VTS = "vts",
    BEP2 = "bep2",
    SXP = "sxp",
    FTM = "ftm",
    TIA = "tia",
    VET = "vet",
    ONT = "ont",
    XLM = "xlm",
    NANO = "nano",
    XRP = "xrp",
    XTZ = "xtz",
    VSC = "vsc",
    MARO = "maro",
    VITE = "vite",
    WAVES = "waves",
    ARK = "ark",
    XCH = "xch",
    XDB = "xdb",
    WAX = "wax",
    XMR = "xmr",
    KYVE = "kyve",
    XPRT = "xprt",
    ZEN = "zen",
    ZIL = "zil",
    SGB = "sgb",
    ZEC = "zec",
    ZETA = "zeta",
    SMARTCHAIN = "smartchain",
    THETA = "theta",
    NIBI = "nibi",
    KAVAEVM = "kavaevm",
    ONE = "one",
    DIONE = "dione",
    SMART = "smart",
    ARBNOVA = "arbnova",
    FSN = "fsn",
    AXELAR = "axelar",
    MERLBTC = "merlbtc",
    PSL = "psl",
    BNB = "bnb",
    HECO = "heco",
    UNKNOWN = "",
    RON = "ron",
    SEI = "sei",
    LAVA = "lava",
    AIX = "aix",
    NAC = "nac",
    POKT = "pokt",
    XYM = "xym",
    XAI = "xai",
    JOYSTREAM = "joystream",
    VENOM = "venom",
    ERG = "erg",
    NEON = "neon",
    XRD = "xrd",
    IOTX = "iotx",
    TARA = "tara",
    WAN = "wan",
    IRON = "iron",
    MAIN = "main",
    AZERO = "azero",
    BDX = "bdx",
    FITFI = "fitfi",
    REI = "rei",
    HTR = "htr",
    BLAST = "blast",
    PIX = "pix",
    BRISE = "brise",
    CFX = "cfx",
    CHZ2 = "chz2",
    NEO_LEGACY = "Neo Legacy",
    DOGECHAIN = "dogechain",
    HMND = "hmnd",
    DOT = "dot",
    OPBNB = "opbnb",
    STRK = "strk",
    EVMOS = "evmos",
    STEEM = "steem",
    LINEA = "linea",
    STRAX = "strax",
    MXC = "mxc",
    SEIEVM = "seievm",
    OKT = "okt",
    NBS = "nbs",
    SAGA = "saga",
    TAO = "tao",
    ONG = "ong",
    LUMIA = "lumia",
    ETHW = "ethw",
    MAPO = "mapo",
    EWT = "ewt",
    GLMR = "glmr",
    WIT = "wit",
    AE = "ae",
    FRA = "fra",
    CRO = "cro",
    ETN = "etn",
    APTOS = "aptos",
    CRONOS = "cronos",
    CLORE = "clore",
    AR = "ar",
    ARDR = "ardr",
    ASTR = "astr",
    DASH = "dash",
    APT = "apt",
    DYM = "dym",
    ENJ = "enj",
    MANTA = "manta",
    FET = "fet",
    FIL = "fil",
    FIO = "fio",
    BTC = "btc",
    FLR = "flr",
    BTG = "btg",
    COREUM = "coreum",
    N3 = "n3",
    CSPR = "cspr",
    INJ = "inj",
    KMD = "kmd",
    DESO = "deso",
    DYDX = "dydx",
    ETC = "etc",
    LUKSO = "lukso",
    MINA = "mina",
    MOVR = "movr",
    FIRO = "firo",
    ELA = "ela",
    ELF = "elf",
    HIVE = "hive",
    ICX = "icx",
    IRIS = "iris",
    DGB = "dgb",
    KDA = "kda",
    SC = "sc",
    SCRT = "scrt",
    PHANTASMA = "phantasma",
    NEO3 = "neo3",
    STX = "stx",
    OSMO = "osmo",
    TAIKO = "taiko",
    TLOSEVM = "tlosevm",
    PIVX = "pivx",
    PULSE = "pulse",
    ROSE = "rose",
    SOL = "sol",
    WEMIX = "wemix",
    CORE = "core",
    XEM = "xem",
    VARA = "vara",
    XVG = "xvg",
    AVAXC = "avaxc",
    LBC = "lbc",
    NIM = "nim",
    AURAN = "auran",
    XDC = "xdc",
    XEC = "xec",
    ROOT = "root",
    ALPH = "alph",
    ALEO = "aleo",
    BTS = "bts",
    STT = "stt",
    OKC = "okc",
    KAR = "kar",
    XNA = "xna",
    ONE_BAND_ONE = "1band1",
    REEF = "reef",
    EXP = "exp",
    WATER = "water",
    OLT = "olt",
    FRAEVM = "fraevm",
    POLYX = "polyx",
    KLAY = "klay",
    VIC = "vic",
    CANTO = "canto",
    TENET = "tenet",
    ESPACE = "espace",
    SLF = "slf",
    ARRR = "arrr",
    DFI = "dfi",
    LIGHTNING = "lightning",
    BLOCX = "blocx",
    CTK = "ctk",
    TT = "tt",
    ARCH = "arch",
    XPR = "xpr",
    ZANO = "zano",
    SPACE = "space",
    EVC = "evc",
    LTO = "lto",
    MNT = "mnt",
    PARTISIA = "partisia",
    STATEMINE = "statemine",
    ZKLNOVA = "zklnova",
    KMA = "kma",
    DAG = "dag",
    PLCU = "plcu",
    OMNI = "omni",
    VLX = "vlx",
    TLOS = "tlos",
    ROOK = "rook",
    GMMT = "gmmt",
    NEER = "neer",
    XPLL = "xpll",
    PDEX = "pdex",
    DERO = "dero",
    FLUX = "flux",
    KUSAMA = "kusama",
    PICA = "pica",
    GLQ = "glq",
    OORT = "oort",
    ORAI = "orai",
    SCR = "scr",
    GRS = "grs",
    OMN = "omn",
    FB = "fb",
    VSYS = "vsys",
    AVAIL = "avail",
    OP = "op",
    KAI = "kai",
    BEAM = "beam",
    DIVI = "divi",
    BLD = "bld",
    CCD = "ccd",
    NOM = "nom",
    BAJU = "baju",
    HAQQ = "haqq",
    DOTASSETHUB = "dotassethub",
    COTI = "coti",
    DVPN = "dvpn",
    FILEVM = "filevm",
    MTL = "mtl",
    NTRN = "ntrn",
    BB = "bb",
    ENDURANCE = "endurance",
    ABBC = "abbc",
    FIRMA = "firma",
    XFI = "xfi",
    FTN = "ftn",
    ACA = "aca",
}